export type TangramLanguage = 'nl' | 'en';

export const DEFAULT_TANGRAM_LANGUAGE: TangramLanguage = 'nl';

const DUTCH: Record<string, string> = {
  'Move left': 'Ga links',
  'Move right': 'Ga rechts',
  Jump: 'Spring',
  'Parade paused': 'Parade gepauzeerd',
  'Tangram pause': 'Tangram pauze',
  'The simulation is frozen. Take a breath, then jump back into the route.':
    'Het spel staat stil. Adem even rustig en ga daarna verder.',
  'Resume run': 'Ga verder',
  'Restart level': 'Level opnieuw',
  'Back to school map': 'Terug naar de schoolkaart',
  'Sound: Off': 'Geluid: Uit',
  'Sound: On': 'Geluid: Aan',
  'Turn sound on': 'Zet geluid aan',
  'Mute sound': 'Zet geluid uit',
  'How to play': 'Zo speel je',
  'Open how to play and settings': 'Open uitleg en instellingen',
  'Start adventure': 'Start avontuur',
  'Pick a classmate and jump through the school.': 'Kies een klasgenoot en spring door de school.',
  'Penguins of Tangram': 'Pinguins van Tangram',
  'Choose class': 'Kies klas',
  'Reset the adventure and start again?': 'Avontuur wissen en opnieuw beginnen?',
  'Badges collected': 'Verzamelde badges',
  'Motion: Reduced': 'Beweging: Minder',
  'Motion: Normal': 'Beweging: Normaal',
  'Route notes: On': 'Route-notities: Aan',
  'Route notes: Off': 'Route-notities: Uit',
  'Reset campaign': 'Campagne opnieuw',
  'Close': 'Sluiten',
  'Tangram helper': 'Tangram hulp',
  'Move, jump, collect badges, and ring the bell. Falling is okay: checkpoints remember your place.':
    'Beweeg, spring, verzamel badges en luid de bel. Vallen is niet erg: checkpoints onthouden je plek.',
  Keyboard: 'Toetsenbord',
  'Arrow keys or A/D move. Space, W, or Up jumps.':
    'Met pijltjes of A/D beweeg je. Met Spatie, W of Omhoog spring je.',
  Touch: 'Aanraken',
  'Use the big buttons on the screen to move and jump.':
    'Gebruik de grote knoppen op het scherm om te bewegen en springen.',
  'Tap ahead or behind the player to move. Tap the big circle to jump.':
    'Tik voor of achter de speler om te bewegen. Tik op de grote cirkel om te springen.',
  Pause: 'Pauze',
  'Press P or Escape, or choose Pause.': 'Druk op P of Escape, of kies Pauze.',
  'Reset the school map and start again?': 'Schoolkaart wissen en opnieuw beginnen?',
  'Open school map': 'Open schoolkaart',
  'Tangram school adventure': 'Tangram schoolavontuur',
  'Pick a classmate, run and jump through five school zones, collect badges, and ring the festival bell.':
    'Kies een klasgenoot, ren en spring door vijf schoolzones, verzamel badges en luid de feestbel.',
  'Every class is fun to play. Try different classmates to find your favorite.':
    'Elke klas is leuk. Probeer verschillende klasgenoten en kies je favoriet.',
  'School map': 'Schoolkaart',
  'Five-zone adventure': 'Avontuur met vijf zones',
  'Finish a zone to open the next one. You can replay any finished zone whenever you like.':
    'Maak een zone af om de volgende te openen. Je kunt elke afgelopen zone opnieuw spelen.',
  Completed: 'Afgerond',
  Unlocked: 'Open',
  Locked: 'Dicht',
  badges: 'badges',
  'Personal best: ': 'Persoonlijk record: ',
  'No personal best yet': 'Nog geen persoonlijk record',
  'Local notes: ': 'Lokale notities: ',
  tries: 'pogingen',
  average: 'gemiddeld',
  falls: 'keer gevallen',
  'checkpoint uses': 'checkpoint-gebruiken',
  'Campaign complete': 'Campagne afgerond',
  'Zone complete': 'Zone afgerond',
  'School festival complete!': 'Schoolfeest afgerond!',
  'Next zone': 'Volgende zone',
  'Replay zone': 'Zone opnieuw',
  'Choose another class': 'Andere klas kiezen',
  Badges: 'Badges',
  Time: 'Tijd',
  Checkpoint: 'Checkpoint',
  Falls: 'Vallen',
  Character: 'Karakter',
  Zone: 'Zone',
  Power: 'Kracht',
  'No power-up': 'Geen power-up',
  'Super snack active': 'Super snack actief',
  'Choose a Tangram classmate, then open the school map.':
    'Kies een Tangram-klasgenoot en open daarna de schoolkaart.',
  'Pick any unlocked zone on the school map.': 'Kies een open zone op de schoolkaart.',
  'Next route': 'Volgende route',
  MOVE: 'BEWEEG',
  CHECK: 'CHECK',
  'RING!': 'LUID!',
  'CHARGE READY': 'KLAAR OM TE STORMEN',
  'CHARGE!': 'STORM!',
  'STOMPS: ': 'SPRONGEN: ',
  TANGRAM: 'TANGRAM',
  'CLASSROOM MAZE': 'KLASLOKAAL-DOOLHOF',
  'LIBRARY + ART': 'BIBLIOTHEEK + KUNST',
  'SPORTS DAY': 'SPORTDAG',
  Penguin: 'Pinguin',
  Crocodile: 'Krokodil',
  Monkey: 'Aap',
  Turtle: 'Schildpad',
  Kangaroo: 'Kangoeroe',
  Lion: 'Leeuw',
  'Penguins Class': 'Pinguinklas',
  'Crocodiles Class': 'Krokodillenklas',
  'Monkeys Class': 'Apenklas',
  'Turtles Class': 'Schildpaddenklas',
  'Kangaroos Class': 'Kangoeroeklas',
  'Lions Class': 'Leeuwenklas',
  'The cheerful Tangram lead with a balanced, confident platforming style.':
    'De vrolijke Tangram-leider met een fijne, stevige springstijl.',
  'A sturdy classmate with a bold grin and a backpack built for adventure.':
    'Een sterke klasgenoot met een grote glimlach en een avontuurlijke rugzak.',
  'A playful, energetic friend who treats every bench and bar like a jungle gym.':
    'Een speelse, energieke vriend die van elke bank een klimrek maakt.',
  'A calm explorer who turns every school trip into a cozy expedition.':
    'Een rustige ontdekker die van elke schooltocht een fijne reis maakt.',
  'A springy sports-day star who is always ready to bound ahead.':
    'Een springende sportdagster die altijd vooruit wil huppen.',
  'A brave hall hero with festival-leader energy and a sunny roar.':
    'Een dappere held met de energie van een feestleider en een zonnige brul.',
  'Balanced all-rounder with reliable jumps.': 'Handig in alles met betrouwbare sprongen.',
  'Heavier landings, steadier recovery after danger.': 'Stevige landingen en rustig herstel na gevaar.',
  'Quick acceleration for playful platform links.': 'Snel optrekken voor vrolijke sprongen tussen platforms.',
  'Safer recovery window after spills and bumps.': 'Meer tijd om te herstellen na morsen en botsen.',
  'Highest jump arc for the tallest routes.': 'De hoogste sprongen voor de hoge routes.',
  'Fastest dash for long sports-day straightaways.': 'De snelste renner voor lange rechte sportbanen.',
  'School Gate Morning Run': 'Ochtendrun bij de schoolpoort',
  'Playground Adventure': 'Avontuur op het speelplein',
  'Classroom Maze': 'Doolhof in het klaslokaal',
  'Library and Art Room Secrets': 'Geheimen van bibliotheek en kunstruimte',
  'Sports Day Finale': 'Finale van de sportdag',
  'Race from the gate through benches, monkey bars, and the opening badge line.':
    'Ren vanaf de poort langs banken, klimrekken en de eerste badge-route.',
  'Bounce across jungle-gym platforms and race over the slide-yard set piece.':
    'Spring over klimrek-platforms en ren langs het grote speelpleinstuk.',
  'Thread through desk islands, chalk shelves, and a winding classroom obstacle lane.':
    'Ga langs eilandjes van bureaus, krijtplanken en bochten in het klaslokaal.',
  'Climb book stacks, thread art-room rafters, and find the hidden badge route overhead.':
    'Klim over boekstapels en kunstraffers en vind de geheime badge-route boven je.',
  'Sprint over hurdles, podium lifts, and the final stadium banner before the school celebration ends.':
    'Ren over horden en podia naar de laatste stadionbanner voor het feest eindigt.',
  'Use the big buttons or arrow keys to move. Try a jump, then ring the bell. Badges are bonus fun.':
    'Gebruik de grote knoppen of pijltjes om te bewegen. Probeer te springen en luid de bel. Badges zijn extra leuk.',
  'Use the bounce pads to reach the monkey-bar route.': 'Gebruik de springplanken voor de klimrek-route.',
  'Hop from desk to desk and use the chalk-tray shelves to cut corners.':
    'Spring van bureau naar bureau en gebruik de krijtplanken als korte route.',
  'The secret route hides above the bright art-room banners.':
    'De geheime route ligt boven de felle banners van de kunstruimte.',
  'This final route rewards clean speed and confident jumps.':
    'Op deze laatste route helpen snelheid en dappere sprongen.',
  'School Gate': 'Schoolpoort',
  'Playground Gate': 'Speelpleinput',
  'Homeroom Door': 'Klasdeur',
  'Library Door': 'Bibliotheekdeur',
  'Sports Gate': 'Sportpoort',
  'Festival Bell': 'Feestbel',
  'Climber Banner': 'Klimmerbanner',
  'Class Bell Rope': 'Klasbelkoord',
  'Roof Signal Bell': 'Dakbel',
  'Sports Day Bell': 'Sportdagbel',
  'Library Steps': 'Bibliotheektrap',
  'Swing Midway': 'Schommel-halverwege',
  'Window Middle': 'Raam-halverwege',
  'Art Room Midway': 'Kunstruimte-halverwege',
  'Podium Midway': 'Podium-halverwege',
  'Super Snack': 'Super snack',
  'Rocket Juice': 'Raketdrank',
  'Focus Snack': 'Focus-snack',
  'Painter Snack': 'Kunstenaars-snack',
  'Victory Snack': 'Overwinningssnack',
  'Relay Captain': 'Estafettekapitein',
  'Checkpoint reached: ': 'Checkpoint bereikt: ',
  'Badges collected: ': 'Badges verzameld: ',
  'Secret found: ': 'Geheim gevonden: ',
  'Power snack active — race ahead while it lasts.':
    'Power snack actief — ren snel zolang het duurt.',
  'Nice stomp! Keep the class parade moving.': 'Goed gesprongen! Ga door met de klassenparade.',
  'A critter bumped you back to safety.': 'Een beestje duwde je terug naar een veilige plek.',
  'Start again from the checkpoint.': 'Begin opnieuw bij het checkpoint.',
  ' sent you back to the checkpoint.': ' stuurde je terug naar het checkpoint.',
  ' before ringing the bell.': ' voordat je de bel luidt.',
  'You still need ': 'Je hebt nog ',
  ' more Tangram badges.': ' Tangram-badges nodig.',
  Play: 'Speel',
  'Zone 1': 'Zone 1',
  'Zone 2': 'Zone 2',
  'Zone 3': 'Zone 3',
  'Zone 4': 'Zone 4',
  'Zone 5': 'Zone 5',
  Penguins: 'Pinguins',
  Monkeys: 'Apen',
  Turtles: 'Schildpadden',
  Crocodiles: 'Krokodillen',
  Lions: 'Leeuwen',
  Slides: 'Glijbanen',
  Swings: 'Schommels',
  Climbers: 'Klimrekken',
  Finish: 'Finish',
  Desks: 'Bureaus',
  Cubbies: 'Kastjes',
  Chalk: 'Krijt',
  'Bell Rope': 'Belkoord',
  Stacks: 'Boekstapels',
  'Reading Nook': 'Leeshoek',
  'Art Room': 'Kunstruimte',
  Finale: 'Finale',
  Track: 'Baan',
  'Long Jump': 'Ver springen',
  'Rooftop': 'Dak',
  'Stand rail': 'Tribunebalk',
  'Top shelf': 'Bovenste plank',
  Bench: 'Bank',
  'Monkey bars': 'Klimrek',
  'Ribbon ledge': 'Lint-rand',
  'Story bench': 'Verhaalbank',
  'Library rail': 'Bibliotheekbalk',
  'Secret chalk shelf': 'Geheime krijtplank',
  'Bell step': 'Belstap',
  'Bell rope': 'Belkoord',
  'Slide ramp': 'Glijbaanhelling',
  'Monkey bar start': 'Begin klimrek',
  'Monkey bar high route': 'Hoge klimrek-route',
  'Swing seat': 'Schommelzitje',
  'Swing beam': 'Schommelbalk',
  'Secret bridge': 'Geheime brug',
  'Climber rung': 'Klimrek-trede',
  'Climber crown': 'Klimrek-top',
  'Desk 1': 'Bureau 1',
  'Desk 2': 'Bureau 2',
  'Chalk tray': 'Krijtbak',
  'Cubby top': 'Kastjestop',
  'Window sill': 'Vensterbank',
  'Banner rail': 'Bannerbalk',
  'Shelf 1': 'Plank 1',
  'Shelf 2': 'Plank 2',
  'Secret rope route': 'Geheime touwroute',
  'Book stack 1': 'Boekstapel 1',
  'Book stack 2': 'Boekstapel 2',
  'Reading rail': 'Leesbalk',
  'Banner loft': 'Bannerzolder',
  'Rafter secret': 'Geheime dakbalk',
  'Art-room spring': 'Kunstruimte-sprong',
  'Long-jump board': 'Ver-springplank',
  'Long-jump lift': 'Ver-springlift',
  'Podium 1': 'Podium 1',
  'Podium 2': 'Podium 2',
  Hurdle: 'Horde',
  'Final podium': 'Eindpodium',
  'Victory banner': 'Overwinningsbanner',
  'Gate badge': 'Poortbadge',
  'Bench badge': 'Bankbadge',
  'Monkey bars badge': 'Klimrekbadge',
  'Ribbon badge': 'Lintbadge',
  'Parade badge': 'Paradebadge',
  'Story badge': 'Verhaalbadge',
  'Rail badge': 'Balkbadge',
  'Secret shelf badge': 'Geheime plankbadge',
  'Field badge': 'Veldbadge',
  'Bell steps badge': 'Belstappenbadge',
  'Bell lawn badge': 'Belveld-badge',
  'Bell rope badge': 'Belkoordbadge',
  'Slide badge': 'Glijbaanbadge',
  'Monkey bar badge': 'Klimrekbadge',
  'High monkey bar badge': 'Hoge klimrekbadge',
  'Play yard badge': 'Speelpleinbadge',
  'Swing badge': 'Schommelbadge',
  'Swing beam badge': 'Schommelbalkbadge',
  'Secret bridge badge': 'Geheime brugbadge',
  'Climber field badge': 'Klimrekveld-badge',
  'Climber badge': 'Klimrekbadge',
  'Climber crown badge': 'Klimrektop-badge',
  'Finish lawn badge': 'Finishveld-badge',
  'Door badge': 'Deurbadge',
  'Desk badge 1': 'Bureaubadge 1',
  'Desk badge 2': 'Bureaubadge 2',
  'Chalk tray badge': 'Krijtbakbadge',
  'Hallway badge': 'Gangbadge',
  'Cubby badge': 'Kastjesbadge',
  'Window badge': 'Vensterbankbadge',
  'Banner badge': 'Bannerbadge',
  'Maze floor badge': 'Doolhofvloer-badge',
  'Shelf badge 1': 'Plankbadge 1',
  'Shelf badge 2': 'Plankbadge 2',
  'Secret rope badge': 'Geheimetouwbadge',
  'Book badge 1': 'Boekbadge 1',
  'Book badge 2': 'Boekbadge 2',
  'Reading badge': 'Leesbadge',
  'Rafter badge': 'Dakbalkbadge',
  'Paint shelf badge': 'Verfplankbadge',
  'Canvas bridge badge': 'Canvasbrugbadge',
  'Lantern badge': 'Lantaarnbadge',
  'Rooftop badge': 'Dakbadge',
  'Score banner badge': 'Scorebanner-badge',
  'Stand rail badge': 'Tribunebalkbadge',
  'Podium badge 1': 'Podiumbadge 1',
  'Podium badge 2': 'Podiumbadge 2',
  'Podium lawn badge': 'Podiumveld-badge',
  'Hurdle badge 1': 'Hordebadge 1',
  'Hurdle badge 2': 'Hordebadge 2',
  'Sprint badge': 'Sprintbadge',
  'Long-jump badge': 'Ver-springbadge',
  'Track badge': 'Baanbadge',
  'Final podium badge': 'Eindpodium-badge',
  'Victory banner badge': 'Overwinningsbanner-badge',
  'Puddle lane': 'Plasbaan',
  'Narrow puddle': 'Smalle plas',
  'Sandbox puddle': 'Zandbakplas',
  'Tire-track puddle': 'Bandenspoorplas',
  'Spilled paint': 'Gemorste verf',
  'Glue puddle': 'Lijmplas',
  'Ink puddle': 'Inktplas',
  'Final lane puddle': 'Plas op de eindbaan',
  'Traveling slide': 'Bewegende glijbaan',
  'Rolling desk': 'Rijdend bureau',
  'Slide spring': 'Glijbaan-sprong',
  'Swing spring': 'Schommel-sprong',
  'Long-jump spring': 'Ver-springsprong',
  'Victory spring': 'Overwinningssprong',
  'Water jump': 'Watersprong',
  'Score banner': 'Scorebanner',
  'Judge table': 'Jurytafel',
  'Judge table badge': 'Jurytafel-badge',
  'Lantern beam': 'Lantaarnbalk',
  'Rooftop gate': 'Dakpoort',
  'Podium': 'Podium',
};

export function isTangramLanguage(value: unknown): value is TangramLanguage {
  return value === 'nl' || value === 'en';
}

export function tangramText(language: TangramLanguage, value: string): string {
  if (language === 'en') return value;
  const direct = DUTCH[value];
  if (direct) return direct;
  if (value.startsWith('Checkpoint reached: ')) {
    return `${DUTCH['Checkpoint reached: ']}${tangramText(language, value.slice(20))}`;
  }
  if (value.startsWith('Badges collected: ')) {
    return `${DUTCH['Badges collected: ']}${value.slice(18)}`;
  }
  if (value.startsWith('Secret found: ')) {
    return `${DUTCH['Secret found: ']}${tangramText(language, value.slice(14))}`;
  }
  if (value.endsWith('! Start again from the checkpoint.')) {
    return `${tangramText(language, value.slice(0, -34))}! ${DUTCH['Start again from the checkpoint.']}`;
  }
  if (value.endsWith(' sent you back to the checkpoint.')) {
    return `${tangramText(language, value.slice(0, -33))}${DUTCH[' sent you back to the checkpoint.']}`;
  }
  if (value.endsWith(' before ringing the bell.')) {
    return `${tangramText(language, value.slice(0, -25))}${DUTCH[' before ringing the bell.']}`;
  }
  if (value.startsWith('You still need ') && value.endsWith(' more Tangram badges.')) {
    return `${DUTCH['You still need ']}${value.slice(15, -21)}${DUTCH[' more Tangram badges.']}`;
  }
  return value;
}

export function tangramLanguageLabel(language: TangramLanguage): string {
  return language === 'nl' ? 'Nederlands' : 'English';
}
